Repository helpfulengineering/ok-validate, pull requests merged in 2021-03, with the labels that each got.

#2 Initial validation via GitHub Actions
  .github/workflows/python-verify.yml
Labels: enhancement

#1 schema bug fix
  .github/workflows/python-verify.yml
  okv/okv.py
  okv/schemas/okh.yaml
Labels: bug, enhancement

#3 Initial github action logic
  .dockerignore
  .github/workflows/push-main.yml
  Dockerfile
  README.md
  action.yaml
  entrypoint.sh
  okv/okv.py
  okv/validators.py
  setup.cfg
Labels: enhancement

#4 fix workflow, schema required fix #patch
  .github/workflows/push-main.yml
  README.md
  okv/schemas/okh.yaml
Labels: bug

#5 update exit logic + gh tag action #patch
  .github/workflows/push-main.yml
  okv/okv.py
Labels: bug

#6 Make GitHub Action friendlier for pull requests
  README.md
  action.yaml
  entrypoint.sh
Labels: enhancement
